### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by siiptuo** [fogre/TiraLab#2]
Ladattu 29.4.2017 17.30

En valitettavasti voinut testata ohjelmaa. Se ei käänny, koska funktiota `findRoute` ei ole määritelty.

Koodityyli kuten sisennys vaihtelee suuresti ohjelman eri osien välillä. Tämän voi helposti korjata esimerkiksi [clang-format](https://clang.llvm.org/docs/ClangFormat.html) tai [astyle](http://astyle.sourceforge.net/) työkaluilla. Tämän lisäksi minusta vaikuttaa, että kaikkea varattua muistia, kuten `main.c`-tiedoston `visited` muuttujaa tai `ipTableTag` kenttää `destinations`, ei ikinä vapauteta. Tällaisia virheitä voi etsiä [Valgrind](http://valgrind.org/)-työkalulla.

`setAddress` funktio on mielestäni harhaanjohtava, koska se ei aseta osoitetta, vaan luo satunnaisen osoitteen. En ymmärrä myöskään miksi funktio ottaa parametrit `mask` ja `id`, koska niiden arvo tallennetaan `ipTable`:n eikä niitä käytetä muualla. Tämän lisäksi `randomAddressGenerator` funktion toimintaa voisi dokumentoida.

Muuten etenkin tiedosto `destinationsCreator.h` ja sen toiminta on hyvin dokumentoitu. Lisäksi testit ja niiden tarkoitus on selitty mainiosti.

**Comment by fogre** [comment]
Kokonaan päivitetty versio ei ilmeisesti ehtinyt ennen katselmointia. Kiitos kommenteista ja etenkin kun huomautit sisennysongelmista, sillä SublimeText näyttää välillä pistävän tekstitiedoston sisennyksen miten sattuu.
